name: Docker CI  
  
on:  
  push:  
    branches: [ main ] 
  pull_request:  
    branches: [ main ] 
  
jobs:  
  
  build:  
  
    runs-on: ubuntu-latest  
  
    steps:  
    - uses: actions/checkout@v4  
  
    - name: Use Node.js 20.x  
      uses: actions/setup-node@v3  # 推荐使用最新版本，当前为v3（请检查最新文档）  
      with:  
        node-version: 20.x    
 
    - name: Build the Docker image  
      run: docker build -t ci_test@v0.01 .  
  
    - name: Login to DockerHub  
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin  
  
    - name: Push the Docker image  
      run: docker push ci_test@v0.01 
