name: Docker CI  
  
on:  
  push:  
    branches: [ main ]  
  
jobs:  
  
  build:  
  
    runs-on: ubuntu-latest  
  
    steps:  
    - uses: actions/checkout@v2  
      
    - name: Build the Docker image  
      run: docker build -t ci_test@v0.01 .  
  
    - name: Login to DockerHub  
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin  
  
    - name: Push the Docker image  
      run: docker push ci_test@v0.01 
